name: Echo Secret

on:
  push:
    branches:
      - main  # This will run the workflow when there is a push to the main branch
  pull_request:
    branches:
      - main  # This will run the workflow on pull requests targeting the main branch

jobs:
  echo-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo secret
        run: echo ${{ secrets.MY_SECRET }}
